### ISSUE TITLE
Use batch_write for engine.save and engine.delete

### ISSUE THREAD

**Issue by xuru** [numberoverzero/bloop#101]
Take advantage of [batch writing](https://boto3.readthedocs.io/en/latest/guide/dynamodb.html#batch-writing) in order to speed up `save` and `delete` engine methods.  It would have to bunch up like models, as the `batch_write` boto3 method is on a per table basis.

> I'd strongly prefer to make it entirely automatic within the existing methods, although we can discuss adding a kwarg to the methods which enables batching.  I'm -1 on adding batch-specific methods to the engine, though. "Use batch operations" answers "how do you want me to <x>" and not "what do you want me to do".

> This could fall under a minor version change, but if it's possible to get into 2.0 then we don't have to worry about it.

**Comment by numberoverzero** [comment]
* [ ] `SessionWrapper` exposes `delete_items` and `save_items`, interface TBD.  Proposal: `delete_items(table_name, items)` and `save_items(table_name, items)`.
* [ ] `Engine.save(...)` and `Engine.delete(...)` could automatically use batch operations when possible, or take an additional kwarg `batch=False` to enable performance.  Proposal: make it fully automatic, thorough documentation about when it is used.
* [ ] Possible API change: do save and delete try to complete as much as possible, or fail on first error?  Currently they fail on first, but the load operation tries to complete as much as possible.  How would that change impact users?  Does anyone rely on fast fail for save/delete, especially since we re-order objects before processing?
* [ ] Docs:
  * [ ] `Engine.save`, `Engine.delete` docstrings
  * [ ] `api/public.rst`
  * [ ] `meta/changelog.rst`
  * [ ] `user/engine.rst`
  * [ ] `CHANGELOG.rst`

I don't think we should drag in a `boto3.resource("dynamodb")` just for the batch writer; if we used it for more operations yes, but we're stuck with a client for now.  There's some batching logic in `session.py` already for loading, maybe it can be refactored to handle load/save/delete batching?

**Comment by numberoverzero** [comment]
Copying my comments from Slack:

> Now I remember why `batch_write_item` was out of the question:
> > BatchWriteItem cannot update items. To update items, use the UpdateItem action.

> This doesn't work with Bloop's concept of shared tables.  (waaay back in ~0.3.0 bloop let you specify if saves should use `PutItem` or `UpdateItem` but that was removed in ~0.7.0 when multiple models could write to the same table)
> That's a bummer; this won't be as straightforward as I thought.
> batch delete is possible (removing the key(s) will necessarily delete the object across rows) but for writes the user would need some way to explicitly allow the use of PutItem.  I'll see if I can dig up the old issues/PRs on this.
> hm, not much in the way of details I'm afraid.  Here's what I found:
>> https://github.com/numberoverzero/bloop/issues/25, https://github.com/numberoverzero/bloop/commit/ad6d724bcf5a6a4e3b9b30edf8406a57788e7e82, https://github.com/numberoverzero/bloop/issues/4

> Within those commits/issues, `bloop.Client` roughly maps to today's `bloop.session.SessionWrapper`

**Comment by numberoverzero** [comment]
Finally reviewing this again, open over a year :( Sorry about that.

Echoing the last update, shared tables make BatchWriteItem (~equivalent to PutItem) a non-starter.  bloop could expose an option to prevent shared tables (`Engine.bind` could fail when a model references an already-seen table) which ensures BatchWriteItem can be safely used.  However, that doesn't address batching conditional operations, and it would require significant changes to the Engine and SessionWrapper.  It adds a bit of cognitive overhead when evaluating the throughput cost of a save/delete call, especially when the condition might be a `bloop.Condition()` that wasn't built up (ie. a for loop over an empty list of conditions to apply).

I'm closing this as won't implement for now.  Happy to reconsider if DynamoDB releases a BatchUpdateItem (even without conditions) or allows conditions in BatchWriteItem (very unlikely).
