### ISSUE TITLE
Support some kind of "NextToken" for queries and scans.

### ISSUE THREAD

**Issue by platta** [numberoverzero/bloop#132]
I've started building a REST API using Bloop to map my business objects to DynamoDB. But, I just realized that I can't properly implement paginated list and search APIs because Bloop doesn't expose the LastEvaluatedKey or have any mechanism for state preservation. There is no way for me to get the "next" page of data on a subsequent API call once the original context is lost.

Do you have plans to, or would you be in favor of, adding support for this type of behavior?

It could be implemented in a similar way to how the AWS CLI does it. If you issue a scan this way:
```
aws dynamodb scan --table=my-table --max-items=3 --page-size=2
```
There are two calls made to DynamoDB, and you'll get three items back. You'll also get a NextToken which is a Base64 encoded string containing the JSON structure:
```JSON
{
    "ExclusiveStartKey": {
        "hashkey": {
            "S": "HASH2"
        }
    },
    "boto_truncate_amount": 1
}
```
The `ExclusiveStartKey` contains the hashkey for the last item returned by the last _completely consumed_ DynamoDB API call. If you pass the NextToken back to the CLI, it will re-execute the second call to DynamoDB, skip `boto_truncate_amount` items (in this case 1), and resume scanning.

Bloop could construct a similar NextToken encoding both the ExclusiveStartKey that needs to be passed to DynamoDB to resume a scan/query enumeration and the number of items Bloop already returned from the current page in the previous request.

I just briefly looked at the code, but my thinking is that a property could be added to the `SearchIterator` class that gets updated in the `__next__` method. Then, there could be an optional parameter to `SearchIterator.__init__` to set its initial value.

Sorry for the wall of text, but I see in other issues you've been very thoughtful and open to discussion so I wanted to get as much of the info out there as I could. I can code the change and submit a PR, but I wanted to get your thoughts on it before I do anything.

**Comment by numberoverzero** [comment]
Thanks for opening an issue and especially thank you for the thorough detail!  While it's not necessary to open an issue, the context you provided saves a lot of time iterating on what functionality you're actually looking for from bloop.

I agree with exposing an option for Scan/Query to start elsewhere from the beginning (ContinuationToken=null) but I'd like to make sure any change doesn't (1) limit future additions too much (2) result in option/configuration hell (so many knobs and dials that common usage is harder).

**Comment by numberoverzero** [comment]
I'm dumping some links that might be relevant to investigation; at minimum these will all probably need updates with the new parameter:

* [search.py source](https://github.com/numberoverzero/bloop/blob/4c95f5a0ff0802443a1c258bfaccecd1758363e7/bloop/search.py)
* [User Guide: Query & Scan](https://bloop.readthedocs.io/en/latest/user/engine.html#query)
* [Public API: QueryIterator](https://bloop.readthedocs.io/en/latest/api/public.html#query)
* [Internal API: Search, PreparedSearch, SearchIterator](https://bloop.readthedocs.io/en/latest/api/internal.html#search)

**Comment by numberoverzero** [comment]
Next, what's the temporary workaround you'd probably use if Bloop didn't support ContinuationToken in some way?  This could help determine how far up the API the parameter needs to go, and what shape you'd usually pass it in.  I think this would be roughly your shim until bloop 2.4:

```python
class Engine(bloop.Engine):
    def query(self, *a, next_token=None, **kw):
        q = super().query(*a, **kw)
        if next_token:
            q.request["ExclusiveStartKey"] = next_token
        return q
```

With the same working for [`Engine.scan`](https://bloop.readthedocs.io/en/latest/api/public.html#bloop.engine.Engine.scan).  I assume you'd use the same token shape for a parallel scan, but that's worth validating.

**Comment by numberoverzero** [comment]
I like your idea for encoding the consumption/offset state in a property of the `SearchIterator` class.  It would be nice to keep the naming similar to the [`Stream`](https://bloop.readthedocs.io/en/latest/api/public.html#bloop.stream.Stream) class and expose something like `SearchIterator.token` and `SearchIterator.move_to(token)`.

Using the constructor is an option, but I'd prefer to keep **existential** parameters (those required for a Search to exist at all) from **usage** parameters (those that manipulate the search state).

In this case, `SearchIterator.move_to(token)` would join `.reset()`, `.all()`, `.first()`, and `.one()` in manipulating the current state of a valid search object.

Thoughts?

**Comment by platta** [comment]
I agree with you about using a `move_to` method instead of the constructor. That's a better fit.

I also think this setup plays nicely with your two concerns - it shouldn't inhibit future additions, and it doesn't require any configuration.

I'll start working on the changes. Hopefully there are no surprise gotchas in the logic.

**Comment by platta** [comment]
Note to self - double check around line 513 in `search.py` for issue when page size coincides with record count.

Change
```
while (not self._exhausted) and len(self.buffer) == 0:
```

To
```
while (not self._exhausted) and len(self.buffer) <= 1:
```

To resolve. Not sure if this is specific to using DynamoDB Local.

**Comment by numberoverzero** [comment]
I've only spent a few minutes thinking about this so you may have considered it already.  Looking at the commit above, is there a need to track anything besides `ExclusiveStartKey` in the token?  That value doesn't need to be exactly what's returned from DynamoDb, we can set our own by tracking the last key that was yielded from the buffer.

For example, the first page of results is buffered into the `SearchIterator` class and contains `[a, b, c, d]`.  The following `__next__` and `.token` calls are made:

1. `.token` returns `null`
2. `__next__()` yields `a` and .token now yields `{ESK: a}`
3. `__next__()` yields `b` and .token now yields `{ESK: b}`

This would need a single new variable in `SearchIterator` like `_last_yielded_object` and then `SearchIterator.token` would simply build from that.  Now we don't need to track offset and truncate, right?  The ESK is simply updated whenever `__next__` is called.

Note that this value can't just read `.request["ExclusiveStartKey"]` since that is tracking the last batched call.

The complexity I see is in figuring out which fields to extract from the object to make a valid ExclusiveStartKey; we might need to know the model and index being queried to pull the dynamo_names.

**Comment by numberoverzero** [comment]
Very roughly, and with no suggestion for `extract_key_somehow` yet:

```
class StreamIterator:
    def __init__(self, ...):
        self._last_yielded = None

    @property
    def token(self):
        return {
            "last_evaluated": self._last_yielded
        }

    def __next__(self):
        ...
        if self.buffer:
            obj = self.buffer.popleft()
            self._last_yielded = extract_key_somehow(obj)
            return obj
```

**Comment by platta** [comment]
I implemented it to create a token consisting of:
- The `LastEvaluatedKey` that was used to pull the _current_ page of data (as you noted, we can't use the one from `.request`).
- The number of items from the current page we have already popped from the buffer.
- The current values for `scanned` and `count` so they will remain accurate after calling `move_to()`.

Looks like Travis didn't like my PR, going to go check that out.

**Comment by numberoverzero** [comment]
I hadn't considered persisting the count/scanned values, but that's an interesting idea.

When would a user be able to rely on those numbers?  Unlike the stream token which is for an append-only data store, the counters could drift for a scan or query.  For a long-lived token and mutable random access data they will almost certainly be incorrect.

Those values would also represent the number scanned or counted since the beginning (ESK=null) of the query, which may not be where the user started (for example, they want the count/scanned since they continued from the token).

**Comment by platta** [comment]
To be honest, I didn't give much consideration to the _use_ of count/scanned. I just considered them part of the "state" of the iterator, and decided to carry them along with the token so that `move_to()` could fully restore that state. I did make sure not to count pages twice - the last page pulled in one iterator and the first page pulled by the "continued" iterator are the same, so I did not increment those counters in that case.

If you scan an entire table resulting in `scanned == 100` and `count == 100`, I wanted those values to be the same at the end whether you used a single iterator or used tokens to continue the operation across multiple instances.

So, from the perspective of reaching the same end value regardless of how many times you grabbed a token and "continued" on another iterator, this makes sense to me. I didn't think of the fact that a user might want to see the counters specific to just the current iterator.

**Comment by platta** [comment]
In theory, iterators could expose two sets of `scanned` and `count` properties so you could read both the total across an entire search and the values specific to the current iterator. I'm happy to change or implement whichever way you think makes the most sense.

**Comment by numberoverzero** [comment]
Hey @platta sorry I haven't been very responsive on this.  I'm fairly saturated at work right now but I want to get to this in the next week.

I've spent some time thinking about it, and I have two high-level comments:

1. Rather than assume a b64 encoding, can the token simply be a dict of basic types?  That allows users to choose a compact storage format if needed (ie. value-only bytes for fixed keys to densely store many tokens) or a verbose option if they want to pass around the entire context for eg. logging.
2. I think the types of information that can be stored in a token sort of fall into three categories: intrinsic details of the search iterator (for example, table name or index) which do not change; consistent state of the iterator (for example, exclusive start key will be the same regardless of how much time has passed); and finally inconsistent state of the iterator (for example, count which may be invalid if the token is very infrequently used w.r.t. table mutation rate).  I'm not convinced that all three belong in a token, especially the last category.  There's an argument that the first shouldn't be there either (Stream tokens don't encode all stream intrinsics).

Thanks for your patience and especially for opening an issue and even providing a working implementation!

**Comment by platta** [comment]
No worries, I'm totally swamped at work right now, too.

For your first item - are you saying you'd prefer `token` to be returned as a dict and for `move_to()` to expect a dict as input? That's essentially saying the encoding/decoding are out of scope as far as Bloop is concerned. I wouldn't fight you on that, it certainly keeps the library more focused on the core of what it does.

For the second item - I agree 100% on the first category. Every AWS API that uses continuation tokens expects you to pass the intrinsic details on all subsequent calls, just with the addition of the token. If you follow that pattern, there's no reason for the token to have that information.

The third category I don't have a strong opinion on. I hadn't thought about the inconsistency of those properties over time, but your point about that is totally valid.

So, I'm happy to update my fork to
- Remove encoding/decoding of tokens
- Remove storing/restoring the `count` and `scanned` properties.

Are there any other changes you'd like to see?

**Comment by numberoverzero** [comment]
I'll give it some deeper thought tonight but yes, I think those are the two api level changes I'd like to see.

---

I have given implementation some thought this week; there might be a simplification available for replay logic at the expense of some token generation complexity.  Since each item returned from the iterator is **almost** an ExclusiveStartKey (it's a superset of properties in all cases) we could remove the need to track `bloop_page_offset` by converting the yielded item into an ESK.

For example, to convert the following into an ESK on a table query (no index):

```
{
    "pk": {"S": "foo"},
    "attr": {"S": "bar"},
    "hk": {"N": "3"},
    "data": {"N": "4.2"}
}
```

we'd need to drop the `attr/data` fields and get:
```
{
    "pk": {"S": "foo"},
    "hk": {"N": "3"},
}
```

which can't be done in the `SearchIterator` class (since it doesn't know about which keys are relevant) but **can** be done in the `SearchModelIterator` class since it knows which Model and Index are being queried.

Ignoring the implementation of row -> esk for a second, that would give the following:

```
class SearchIterator:
    _last_yielded = None

    def __next__(self):
        ...
        ret = ...  # existing code

        self._last_yielded = ret
        return ret

    @property
    def token(self):
        if not self._last_yielded:
            return None  # TODO or {"ExclusiveStartKey": None} for forward compat?
        return {"ExclusiveStartKey": self._extract_esk(self._last_yielded)}

    def move_to(self, token):
        self.request["ExclusiveStartKey"] = token["ExclusiveStartKey"]

    def _extract_esk(self, obj: dict) -> dict:
        raise NotImplementedError


class SearchModelIterator:
    def _extract_esk(self, obj: dict) -> dict:
        # TODO implement
        pass
```

Notice that in this case the impl for `__next__` doesn't have to change, it just keeps track of the last blob handed back.  It should be flexible enough that if the ESK format ever changes (such that you can't derive it from the last_yielded value) we can still put that logic in `_extract_esk`.

**Comment by platta** [comment]
I like your thinking here. Two things:

1. I never thought about just generating my own `ExclusiveStartKey` because I didn't want to assume I knew what AWS puts in there. There's a certain safety in just reusing what DynamoDB gives you and adding the page offset. As long as you have confidence that the format won't change this is a better solution than tracking the page offset.

2. If we're going to rely on the structure of `ExclusiveStartKey`, why not use `LastEvaluatedKey` to inform us on which fields to include from the row? Wait, nevermind. If the query from DynamoDB doesn't return a `LastEvaluatedKey` then you don't have anything to go on, so you're right.

I'll try to put an implementation into my fork for you to review. I'm traveling next week so maybe I'll have some downtime at the airport.

**Comment by numberoverzero** [comment]
Correct on the second point; we know what structure they use for LEK because it's always the set `{index keys} + {table keys}` where for table queries index keys are null.  For non-table queries the table keys are used to uniquely identify an ESK.

Your first point is fairly important, and in general I would shy away from exploiting implementation details like this.  In this specific case I'm confident we can rely on the implementation to be stable; most changes they could make would increase both compute time and storage costs.  Consider two alternative implementations:

1) **opaque token such as a GUID**: this will require an indirection to load which adds some latency (worst case a full network request per token on cache miss, and Dynamo is very sensitive to latency) as well as some amount of compute to invalidate those over time, and handle cross-user security (I copy a token off your account and make authn'd calls in my account)
2) **symmetric encryption of the token**: indirection to load the key (mitigated by caching, modulo async rotation) and extra compute to encrypt/decrypt, keeping in mind each row could be up to 4kB and in the degenerate case that's entirely in the pk (even larger for customers with expanded key limits)

They could make changes to the wire format which reduces bytes on the wire and deserialization time though.  For example FlatBuffers or Cap'n'Proto for zero copy deserialization but in that case we fall back to using the raw token + offset tracking again (which can be done in the `_extract_esk` method) or figure out the FlatBuffers format (should be easy since they'll need a generic schema given the payload variance).

---

There's an option to put a copy of the loaded object in the token, which makes it easier to make a token manually.  However that could run into issues with users overloading their model's `__new__` that assumes a new instance should eg. load an expensive dependent value.  They shouldn't do that, but I don't think it's fair to assume.  If we could, the following code would work:

```
q = engine.query(Users, key=Users.name=="numberoverzero")

token = {
    "ExclusiveStartKey": User(name="numberoverzero", version=5.2)
}
q.move_to(token)
```

Without using the model instance I'll have to know how to serialize the model to make a token manually.  Maybe that doesn't matter because no one would do this, but it's worth mentioning:


```
q = engine.query(Users, key=Users.name=="numberoverzero")

token = {
    "ExclusiveStartKey": {
        "n": {"S": "numberoverzero"},
        "ver": {"N": "5.2"}
    }
}
q.move_to(token)
```
