### ISSUE TITLE
Serialize model object to JSON

### ISSUE THREAD

**Issue by dhait** [numberoverzero/bloop#135]
A common use case for bloop would be a REST API, where an item queried from DynamoDb is returned to the user as a JSON-encoded field in the HTTP Response "body"

BUT

The python json library does not allow serialization of a model object to a JSON string:

    class MyModel(BaseModel):
        class Meta:
            table_name = 'myTable'
        id = Column(String, hash_key=True)
       name = Column(String)
      email = Column(String)

    json.dumps(MyModel(id='abcd', name='joe', email='joe@home.com')

> Error
> Traceback (most recent call last):
>  ...(snip)...
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
> raise TypeError(f'Object of type {o.\_\_class\_\_.\_\_name\_\_} '
>    TypeError: Object of type Connection is not JSON serializable

I have been unable to figure out a work-around.  Is there fix or other guidance to get this working?

**Comment by numberoverzero** [comment]
Thanks for opening an issue, especially one I suspect users encounter or want for development.  I'm sorry for the slow response.

Providing simple serialization is a great idea (who wants to write their own serialization layer) but the challenge is in non-surprising behavior for the edge cases.  At one time I considered exposing a marshmallow extension #89 but never got to implementation.  From that issue it should still be possible to follow the example of the marshmallow-sqlalchemy library to generate schemas, but since then #26 was implemented and there may be extra work for model inheritance (or none at all, if the signals fire at the correct times).

As a quick example, here are a few of the challenges for supporting a primitive serialization without going full-blown marshmallow schemas:

* You don't want to expose all columns in the model to the outside world, such as a `Customer` object with a `discount_multiplier` or `pw_hash`.
* You want to serialize the model more than one way eg. for syncing to a legacy system and exporting out the front of a new service.
* You want to serialize a column differently depending on request context eg. using protobuf or base64/json depending on the caller's request headers.

Even if we ignore those and expose `bloop.debug_serialize(some_obj)` there are questions about format for datetime objects, which `json.dump` doesn't natively support.  Should Timestamp be an integer or the ISO8601 string?  What about Datetime?  Should UUID be the str repr or a tuple of ints?

---

However, if you're interested in helping with marshmallow integration (or could even provide some pseudocode of how you'd like to interact with such an integration) I'd be willing to revisit #89 in the future.  I also don't want to think about serialization and it'd be nice to (top of the head api design) generate a schema and serialize with:

```
from bloop.ext.marshmallow import configure, register_type
from bloop import Datetime

configure(autogenerate=True, meta_attr="schema")
register_type(Datetime, lambda x: x.isoformat())


class User(BaseModel):
    ...


user = User(...)
serialized = User.meta.schema().dump(user)
```

**Comment by numberoverzero** [comment]
I started down a path of a full-blown marshmallow integration and quickly realized it was both (1) a lot of syntactic overhead and (2) incomplete and mostly forwarded args to marshmallow object initializers.  Instead, here's a self-contained function you can pass to `json.dumps` to render out an object with some minimal configuration options.  This seems worth adding to the patterns section of the user guide, at the very least.

```python
import base64
import datetime
import decimal
import uuid
from bloop import BaseModel


def serializer(use_float: bool = True, explicit_none: bool = True):
    """
    Pass to ``json.dumps`` as the ``default`` argument to serialize bloop's built-in types.
    Note this serializes against the python type, and not the modeled type.  For example both
    DateTime and Timestamp are serialized in isoformat while you might want Timestamp to serialize
    as a unix timestamp.  You'll need to write your own serializer or leverage a more robust
    library such as marshmallow.

    .. code-block:: pycon

        >>> user = User(...)
        >>> wire = json.dumps(user, default=serializer(explicit_none=False))
        >>> print(wire)
        '{"name": "janet", ...}'

    :param use_float:
        Whether to render decimal.Decimal as a float (causing DESTRUCTIVE LOSS of precision)
        or as a string, eg. Decimal('3.14') as '3.14' or 3.14
    :param explicit_none:
        Whether to omit missing/none/empty values or to render them as an explicit ``null``.
    :return: A function that can be passed as the ``default`` argument to ``json.dumps``
    """
    def default(obj):
        # bloop.Set[T]
        if isinstance(obj, set):
            return list(obj)
        # bloop.{Datetime,Timestamp}
        if isinstance(obj, datetime.datetime):
            return obj.isoformat()
        # bloop.UUID
        elif isinstance(obj, uuid.UUID):
            return str(obj)
        # bloop.Number
        elif isinstance(obj, decimal.Decimal):
            if use_float:
                return float(obj)
            return str(obj)
        # bloop.Binary
        elif isinstance(obj, bytes):
            return base64.b64encode(obj).decode("utf-8")
        # bloop.BaseModel
        elif isinstance(obj, BaseModel):
            return {
                c.name: getattr(obj, c.name, None)
                for c in obj.Meta.columns
                if hasattr(obj, c.name) or explicit_none
            }
        raise TypeError(f"Type {type(obj)} is not serializable")
    return default
```

**Comment by numberoverzero** [comment]
And here's the test file I used to check permutations of nested fields and missing values (render missing columns):

```python
import datetime
import json
import uuid

from bloop import (
    BaseModel, Column,
    
    String, UUID, DateTime, Number,
    Integer, Timestamp, Binary, Boolean,
    Set, List, Map
)

from [PATTERNS] import serializer


class User(BaseModel):
    name = Column(String, hash_key=True)
    uid = Column(UUID)
    dob = Column(DateTime)
    exact_age = Column(Number)
    age = Column(Integer)
    acct_created = Column(Timestamp)
    data = Column(Binary)
    verified = Column(Boolean)
    times = Column(Set(DateTime))
    ids = Column(List(Integer))
    blob = Column(Map(**{
        "first": String,
        "second": Integer,
        "third": List(Integer),
        "d": DateTime
    }))
    missing = Column(DateTime)


n = datetime.datetime.now(tz=datetime.timezone.utc)
user = User(
    name="joe",
    uid=uuid.uuid4(),
    dob=n,
    exact_age=3.14,
    age=3,
    acct_created=n,
    data=b"hello, world",
    verified=False,
    times={n},
    ids=[1, 2, 3],
    blob={"first": "Hello", "second": -12, "third": [0, 0, 2], "d": n},
)


b = json.dumps(
    user, default=serializer(explicit_none=True),
    sort_keys=True,
    indent=2
)
print(b)
```
