### ISSUE TITLE
Support atomic counter at model or engine layer

### ISSUE THREAD

**Issue by huyphan** [numberoverzero/bloop#136]
I would love to see [atomic counter](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters) supported at engine or model layer. I'm not sure what would be the best way to implement this given the current API. But I can imagine one option:

```python
class GlobalIdTrackerModel(BaseModel):
    partition_key = Column(String, hash_key=True)
    search_key = Column(String, range_key=True)
    current_counter = Column(Number)

foo_bar_id_tracker = GlobalIdTrackerModel("foo", "bar")
engine.update(instance=foo_bar_id_tracker, updates=[foo_bar_id_tracker.current_counter.increase(1)])
```
That would require a new method `update()` added to Engine which would eventually call `session.save_item()` (since `save_item()` is just a wrapper for `PutItem` call). 

The code above actually looks weird to my eyes, but that's the best I can think of so far.

**Comment by numberoverzero** [comment]
Thanks for opening an issue!  Today bloop doesn't support the [`"ADD"` action](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD) or [`"DELETE"` action](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.DELETE) in an [UpdateExpression](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions) but we could expose that through, as you mentioned, the `Engine` or maybe the `SessionWrapper`.

I'd like to understand the use case a little better first.  I'm specifically worried about the fact that without idempotency tokens on UpdateItem calls [you can't guarantee an increment happens exactly once in the face of network errors](https://stackoverflow.com/a/9422877).  Quoting from that answer:

> If the connection drops after issuing an UpdateItem ADD request, you have no way of knowing if the add was committed or not, so you don't know if you should retry or not.

In a multi-writer environment **even a conditional update doesn't guarantee execution**.  You need your own idempotency structure eg. an append-only table of modify tokens and a transaction, or an in-row idempotency set of tokens with a conditional update.  These trade off write units (transactions) or space (in-row set) for additional guarantees that the new UpdateExpression actions `ADD` and `DELETE` do not on their own provide.


As to the API it would be fairly easy to [extend the code that builds update expressions](https://github.com/numberoverzero/bloop/blob/4c95f5a0ff0802443a1c258bfaccecd1758363e7/bloop/conditions.py#L362-L377) to support `ADD` and `DELETE` and because the `SessionWrapper` [save and delete methods](https://github.com/numberoverzero/bloop/blob/4c95f5a0ff0802443a1c258bfaccecd1758363e7/bloop/session.py#L60-L80) take full request objects there's no change either.

---

# Some Options

Keeping in mind that today `ADD` only supports numeric types (`bloop.types.Numeric`) and set types (`bloop.types.Set`) while `DELETE` only supports set types, we may need to tie the type system into the update action type.  I could see a few options, roughly sketched out below.  All names placeholders:

### 1. Custom Values Encode Action

Each value carries the action type, such as `bloop.update.Add`, `bloop.update.Delete`.  They represent a delta from the unknown remote value, semantically conveying "add 1 to the value" or "remove this item from the set":
  ```
  class PageView(BaseModel):
      ip = Column(IpAddress, hash_key=True)
      count = Column(Number)
      websites = Set(Url)

  v = PageView(ip='127.0.0.1')

  # increment by 1
  v.count = bloop.update.Add(1)

  # remove a website
  v.websites = bloop.update.Delete(set())
  v.websites.remove("google.com")

  engine.save(v)
  ```

This has the advantage that the type system doesn't need to change, since the renderer would inspect the value and see it's a `bloop.update.Delete` and then pass each value to the typedef.  The downside is that the relative value is probably unusable as it's column's type.  You can't add `3 + some_page_view.count` without knowing it's not a relative value.  Or maybe that's a feature to prevent misuse of absolute vs relative values :)

### 2. Type Provides Action

The other option is that the type now specifies which action should be used in an update expression.  So `bloop.types.Numeric` now serializes into `("ADD", {"N": "2"})` instead of `{"N": "2"}` or `("SET", {"N": "31"})` instead of `{"N": "31"}`.  This would need a major version bump and a deprecation period, and a default action for types in the intermediate.  It keeps things flexible for custom types (eg. DynamicType) which is a significant bonus but comes at the cost of increased complexity to define a custom type (Type._load and Type._dump get more complex as well as any consuming code).

### 3. Don't support `ADD` or `DELETE` Actions

The default action, don't expand beyond Set/Remove.  This is kicking the can down the road should DynamoDB ever add additional actions, say an UPSERT for the MAP type (that's #28, my pipe dream)

### 4. Expose Actions on SessionWrapper or Engine

My least favorite option, since additional functions or arguments make the Engine harder to use.  Do I want to `Engine.save` or `Engine.update` or `Engine.add`?  Even adding a parameter, is it `Engine.save(obj)` or `Engine.save(None, update=obj)` and what about saving multiple objects with some atomic counters?  Can I combine those with conditions?

### 5. Expose Actions on Columns

This one is better than on Engine/SessionWrapper since it reduces the chance to confuse operations or arguments, but breaks the typical `init -> mutate -> engine.save` workflow that bloop streamlines.  I'm defensive of reordering the workflow too much or adding new entry points like `UserModel.balance.add(-19.99)` since it makes dynamic object creation harder.  Today you can use `SomeModel.Meta.columns` and `setattr` to build up an object eg. `setattr(column, column.name, v) while this would require using `getattr(column, action_name)(value)` and storing the resulting object.

---

# Next Steps

I'd prefer 2 (Type Provides Action) then 1 (Custom Value Encodes Action) and least 3 (Don't support ADD or Delete Actions).  I've included 4 and 5 for discussion but I don't think they're on the table.

What I'd find most helpful is an example use case.  Is there an application you're working on today that can't use conditional updates and/or transactions?  Why not?  My guess is some combination of throughput and lack of need for exactness.  If you **can** use conditional updates, here are two examples of their usage (same PageView class above):

```
view = PageView(id='127.0.0.1')
engine.load(view)

# option 1: only require the 'count' column to be unchanged

require_previous = PageView.count == view.count
view.count += 1
engine.save(view, condition=require_previous)


# option 2: require the entire row to be unchanged
view.count += 1
engine.save(view, atomic=True)
```

**Comment by huyphan** [comment]
Thanks for an extremely thoughtful response!

I guess I should have started with some example use case first. Actually I have two:

1. Using DynamoDB to maintain a set of auto-increment counters. This is arguably an anti-pattern in DynamoDB but I would save that for a different topic -- there are still legitimate needs for some sort of auto-increment ID (e.g. bug tracking, case management systems).
2. Using DynamoDB to track the number of visits of website's pages. This is actually coming from your sample code. 

Both use cases have one thing in common: over-counting or under-counting are both not big concerns -- it's okay if we skip some IDs in a bug tracking system or miss some counts for a single web page. In fact, AWS does mention this in their docs regarding atomic counters:

> An atomic counter would not be appropriate where overcounting or undercounting cannot be tolerated (For example, in a banking application). In this case, it is safer to use a conditional update instead of an atomic counter.

Those who choose to use atomic counters *should* already be aware of this and have the right strategy to address (or ignore) potential failures. `bloop` can also help by giving proper caution around the usage of `ADD` or `SET FooBar = FooBar + :incr` once the feature is out. 

---
The lack of this feature is not a blocker for me to achieve what I want, I can totally use some conditional updates as you suggested. However they are not the optimized approach in term of throughput  -- we need to load the item first (which issues `BatchGetItem`) before sending the update. 

What I was hoping is to update the counter and, optionally, receive the whole object back with just one request. Maybe something like this:

```python
obj = PageView(hash_key, range_key)
...
dynamodb_client.update_item(
    TableName=self._compute_table_name(obj.__class__),
    Key=dump_key(self, obj),
    UpdateExpression=f"ADD {column.dynamo_name} :incr",
    ExpressionAttributeValues={":incr": {"N": str(increment)}},
    ReturnValues="ALL_NEW",
)
# probably use unpack_from_dynamodb() to load
# response["Attributes"] into obj
```
--- 
I also prefer your Option 2. That makes the library more extendable in the future. I'm curious what the API would look like if you go with that approach?

**Comment by numberoverzero** [comment]
That example really helps, thank you.  Especially having the functional boto3 call 🎉

I'd like to think about the api a bit more but I think this is achievable.  There are actually two requests here:

1. Some way to use the `ADD` and `DELETE` actions
2. Some way to apply return values to the object after saving

I haven't looked at `ReturnValues` in at least a year so I want to see what the options are like.  I'd probably opt for an equivalent of 'all' or 'all changed' if they exist, and as you mentioned use unpack_from_dynamodb to update the object and mark the attributes as synchronized.

Assuming both of these were implemented, I think the following is what the bloop code would **approximately** look like:

```python
class GlobalConfig(BaseModel):
    key = Column(String, hash_key=True, dynamo_name="k")
    value = Column(DynamicType, dynamo_name="v")


engine.bind(GlobalConfig)


def next_issue_id(engine) -> int:
    cfg = GlobalConfig(
        key="app.next_issue_id"
        value=bloop.update.Add(1)  # <-- TODO decide on syntax
    )
    engine.save(cfg, apply_latest=True)  # <-- TODO decide on syntax
    return int(cfg.value)
```

How does that look ergonomically?  I'm worried about ambiguity of "add to an int" vs "add int to a set" but that could perhaps be left up to the column's type to infer (or add a type hint option).

**Comment by huyphan** [comment]
To me, if the functionality is there and the docs are clear, then ambiguity is not a big concern. Other users might have different opinions though. 

Having said that, I actually like the API syntax of the first option (in your first response) than your latest one. Can we combine your first two options together -- using the API syntax of option 1 and have the underlying implementation as described in option 2? 

That would mean something like this:

```
class PageView(BaseModel):
    ip = Column(IpAddress, hash_key=True)
    count = Column(Number)
    websites = Set(Url)
    category = Column(String) 

v = PageView(ip='127.0.0.1')

# This results ("SET", {"S": "Admin"})
v.category = "Admin"

# This also results ("SET", {"S": "Admin"})
v.category = bloop.update.Set("Admin")

# This results ("ADD", {"N": "1"})
v.count = bloop.update.Add(1)

engine.save(v)
```

**Comment by numberoverzero** [comment]
Agreed with your example.  I was trying that in my previous post but used [`DynamicType`](https://bloop.readthedocs.io/en/latest/api/internal.html#dynamictype) instead of [`Number`](https://bloop.readthedocs.io/en/latest/api/public.html#number) since a config table might be multi-type data :)

Changes we'll need:

1. A new class like `bloop.Actions` with static methods `set`, `delete`, `add`, `remove` that take a single argument, a value.  *(minor version bump)*
2. `Type._dump` will receive either a raw value or a `bloop.Actions` instance but must call `Type.dynamo_dump` with the unwrapped value.  This keeps the most commonly implemented method (`dynamo_dump`) simple but allows customization in the infrequent path (`_dump`) for nested and dynamic types. *(major version bump)*
3. In `conditions.py` there may need to be changes to `sync(obj, engine)` and `ReferenceTracker._value_ref` which both call `engine._dump`. *(minor version bump)*
4. In `ConditionRenderer.render_update_expression` each `value_ref` should be another column name or a `bloop.Actions` instance, so we'll need to have 4 keys in the `updates` dict ("set", "remove", "add", "delete") *(minor version bump)*
5. In `types.py` any nested types that call `_dump` eg. List/Set/Map will need to unwrap the result before using it.
6. A boatload of docs; updated signatures and new sample wire values, changelog and migration guide, custom type section of the user guide.

Signatures for the `Type` class would be:

```
Any -> Type._load -> Any
Union[Any, Action] -> Type._dump -> Action
Any -> Type.dynamo_dump -> Any
Any -> Type.dynamo_load -> Any
```

All of the changes tagged *(minor version bump)* could be added for 2.4.  (2) is a breaking change for anyone that's subclassed Type and implemented `_dump` and needs to come with 3.0.  For example, this would break:

```
class WeirdNumericType(bloop.Type):
    def _dump(self, value, **kwargs):
        # should be in dynamo_dump but maybe bloop docs were confusing
        ((k,v),) = super()._dump(value, **kwargs).items()
        v *= (-1 if v > 100 else 1)
        return {k: v}
```

I don't believe these changes interfere with work for #137.

Anything I'm missing?  This list went deeper into bloop internals so to zoom out, here's what a user would experience (modified from your latest example):

```python
class PageView(BaseModel):
    ip = Column(IpAddress, hash_key=True)
    count = Column(Number)
    websites = Set(Url)
    category = Column(String) 

v = PageView(ip='127.0.0.1')

v.count = bloop.update.Add(1)

# these are identical
v.category = "Admin"
v.category = bloop.Actions.set("Admin")

engine.save(v)
```

**Comment by numberoverzero** [comment]
Interesting that someone could set to a remove action:
```v.count = bloop.Actions.remove(None)```
and that should probably be different than `del`:
```del v.count```

since `hasattr` would be True for the first and false for the second.

**Comment by huyphan** [comment]
The plan you listed there looks solid. I can't think of anything else, but I'm very new to bloop's code base. 

I can totally give this a try and submit a PR if you are not planning to work on this soon. I might be slow though -- for the reason I mentioned above :)

**Comment by numberoverzero** [comment]
I can get started on this fairly soon, I'm finishing up testing for #137 at the moment.

Thanks for the offer!  Do you mind helping with docs?  For example:  where would you look for this feature, what keywords would you search, what user guide sections should mention it?  Anything that should go in the patterns section?

I think I can knock out the user-facing code in a few minutes, the tracking/rendering will take longer.  I'll post edge-case questions back here as they come up.  The previous comment is a good example of what I'd like resolved pre-shipping.

---

I can make this opt-in for 2.4: if you pass in a `bloop.Action` to `Type._dump` you'll get out a `bloop.Action` but everyone else gets the default behavior.  I'll give that a try and potentially you can use this before 3.0.

I still don't like the framework showing through here (`bloop` objects as values instead of transparent mapping) but I'm going to continue.  The update action needs to be passed with the value in some way so I doubt we can escape the syntactic overhead completely.

**Comment by numberoverzero** [comment]
Hey @huyphan would you mind testing this out?

You can install the branch with any of the following (the first two should be faster than the third):

```
# https://stackoverflow.com/a/24811490
pip install https://github.com/numberoverzero/bloop/archive/feature/atomic-counter.tar.gz
pip install https://github.com/numberoverzero/bloop/archive/feature/atomic-counter.zip

# https://codeinthehole.com/tips/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/
pip install git+git://github.com/numberoverzero/bloop.git#egg=feature/atomic-counter
```

Here's a snippet from my manual testing (using `render` avoids waiting for table creation):

```python
from bloop import BaseModel, Engine, Column, Integer, Set, String
engine = Engine()
class Item(BaseModel):
    h = Column(String, hash_key=True)
    r = Column(String, range_key=True)

    strings = Column(Set(String))
    counter = Column(Integer)


from bloop import actions
obj = Item(
    h="hash", r="range",
    strings=actions.delete({"foo", "bar"}),
    counter=actions.add(-10)
)


from bloop.conditions import render
print(render(engine, obj, update=True))
# {
#   'UpdateExpression': 'ADD #n0 :v1 DELETE #n2 :v3',
#   'ExpressionAttributeNames': {'#n0': 'counter', '#n2': 'strings'},
#   'ExpressionAttributeValues': {':v1': {'N': '-10'}, ':v3': {'SS': ['bar', 'foo']}}
# }
```

**Comment by huyphan** [comment]
@numberoverzero: Sure thing. I will give this a try today.

**Comment by huyphan** [comment]
Sorry for coming back late. I finally had a chance to try out the new code today. The new code works flawlessly against my database. 

There's nothing I could complain about this. Thanks for rolling this out so quickly.

**Comment by numberoverzero** [comment]
No problem!  Thanks again for collaborating and especially the early and detailed examples.

The [3.0 milestone](https://github.com/numberoverzero/bloop/milestone/7) is tentatively slated for Sept 13, 2019 and will finalize some of the partial changes made for this issue.  If you have any time in the next few months, it would be great to get a quick check mark that either the head of `releases/3.0` or the c595be4194086e115e386cc6e4a953b3ecc52b8d commit still looks good.

No pressure unless you've got a spare cycle.

```
pip install https://github.com/numberoverzero/bloop/archive/releases/3.0.tar.gz
pip install https://github.com/numberoverzero/bloop/archive/c595be4194086e115e386cc6e4a953b3ecc52b8d.tar.gz
```
