### ISSUE TITLE
Retrieving with get_item()

### ISSUE THREAD

**Issue by antoniocaiazzo** [numberoverzero/bloop#144]
Hi there!
We've been using bloop in our project and up until now it's great. Just a question though: is there a specific reason why the library doesn't use get_item() in case the table only has a primary key and no sort key? According to AWS it's the recommended and fastest way in these cases.
Thanks!

**Comment by numberoverzero** [comment]
Hello, thanks for opening an issue!  I'm really glad bloop is working well for you so far :)

Do you have a reference for the speed difference of `GetItem` and `BatchGetItem` on tables with only a primary key?  I would expect `GetItem` to keep its lead for loading a single item, and to fall behind immediately once the number of items to load is greater than one[0].

For anyone curious about how bloop maps a single `Engine.load` to one or more `dynamodb_client.batch_get_item` calls, here's a few references.  Because bloop will load instances of different models (possibly in different tables)[1] in as few batches as possible, the code to track table names when unpacking objects gets a little complex:

* Call stack: [`Engine.load`](https://github.com/numberoverzero/bloop/blob/f2f71d99efe78951dffc269bccf1d8e48a862652/bloop/engine.py#L188) -> [`SessionWrapper.load_items`](https://github.com/numberoverzero/bloop/blob/f2f71d99efe78951dffc269bccf1d8e48a862652/bloop/session.py#L89) -> [`dynamodb_client.batch_get_item`](https://github.com/numberoverzero/bloop/blob/f2f71d99efe78951dffc269bccf1d8e48a862652/bloop/session.py#L99) -> [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.batch_get_item)
* Docs: [Engine.Load (User Guide)](https://bloop.readthedocs.io/en/latest/user/engine.html#load), [Engine.Load (Public API)](https://bloop.readthedocs.io/en/latest/api/public.html#bloop.engine.Engine.load), [SessionWrapper.load_items (Internal API)](https://bloop.readthedocs.io/en/latest/api/internal.html#bloop.session.SessionWrapper.load_items)

[0] if for no other reason than the http overhead + request signing/validation
[1] otherwise you need two calls to load eg. a `Tweet` object and a `User` object, instead of `engine.load(user, tweet)`

**Comment by antoniocaiazzo** [comment]
Thank you for the thorough explanation. I now understand better how bloop works and realise my mistake, as in I didn't notice bloop was using batch_get_item under the hood.
I have done tests on my project comparing retrieval times of single get_item calls vs a query or a batch_get_item and indeed it's a no brainer: the single get_item calls are much worse performance-wise.

**Comment by numberoverzero** [comment]
Glad things are clearer.  Thanks for opening an issue, I'm sure others had the same question.

I'm going to close this, pull requests for docs are always welcome :)
