### ISSUE TITLE
"module initialization error: Unexpected error while describing ttl"

### ISSUE THREAD

**Issue by urluba** [numberoverzero/bloop#146]
Hi,

I've discovered today an issue with some lambda functions using bloop. Error message was:

"module initialization error: Unexpected error while describing ttl"

https://github.com/numberoverzero/bloop/blob/44e902cc5a126875f1377b7c362e4ca4db152040/bloop/session.py#L192-L195 

Initial code was done at the time of botocore 1.14 and I don't import them with my code meaning that I use(d) those coming with Lambda environment.
I've located a change in botocore 1.16 released in May which may explains the problem: the call to describe_time_to_live now raise exceptions...

https://botocore.amazonaws.com/v1/documentation/api/1.16.0/reference/services/dynamodb.html#DynamoDB.Client.describe_time_to_live

```
Exceptions
    DynamoDB.Client.exceptions.ResourceNotFoundException
    DynamoDB.Client.exceptions.InternalServerError
```

I asked AWS if/when botocore was upgraded to 1.16 to see if it is the root cause. I'll update this post with their answer. Until then take care if you are using the default botocore module, you may set skip_table_setup to True to avoid this issue or import an old version of botocore.

**Comment by numberoverzero** [comment]
Thanks for opening an issue.  At a glance, are you creating the tables when the lambda starts up, or do they exist already?  That would explain why `skip_table_setup` avoids the exceptions for you.

> I asked AWS if/when botocore was upgraded to 1.16 to see if it is the root cause
Is this a github issue we can track, or a private support ticket you've raised?  It would be great to track here.

I wouldn't expect that change to be a root cause here, since it's re-exporting the existing exceptions classes under the client (so you can use `dynamodb_client.exceptions.Whatever` instead of `botocore.exceptions.ClientError`)

---

I did some digging, but don't see any breaking changes.  They started making the exceptions accessible through the client object in 1.16 which is convenient, but they still subclass `ClientError` so the try/except above is fine.

* The [botocore upgrade notes](https://botocore.amazonaws.com/v1/documentation/api/1.16.0/index.html#upgrade-notes) has no mention of the 1.16 exceptions feature.
* It is mentioned in the [github changelog](https://github.com/boto/botocore/blob/b195fc0dd371d5d3033df244722715d5cf96bfb8/CHANGELOG.rst#1160) so maybe they haven't rebuilt the docs recently.  Here's the note: `feature:Exceptions: Added support for parsing modeled exception fields.`
* Here's the [merged pull request](https://github.com/boto/botocore/pull/2037) which looks nice (aside: there's now an [`error_code` property](https://github.com/boto/botocore/blob/6dcea49f1396f8e87a30cecb4b25de0ec0304720/botocore/model.py#L197-L206) that could be used to bubble up the exception name mentioned in #143)

**Comment by urluba** [comment]
The table already exists. I've redeploy a test env and...  you are right: botocore/boto3 versions are not the problem. My code is :(

I've tested with "old" versions of these modules and same behavior:

``` 
[ERROR] 2020-06-17T19:49:57.803Z I am using botocore 1.14.17 and boto3 1.12.11 
[ERROR] 2020-06-17T19:49:57.803Z Unable to Bind Engine()
module initialization error: Unexpected error while describing ttl.
```

I missed something in a prevous release. I have to review the last changes. My apologies for this false issue.

By the way, I am using bloop v3.0.0

**Comment by numberoverzero** [comment]
No problem, good luck resolving the issue!

If there's any debugging info that bloop could expose to help track down problems like this in the future, please feel free to open another issue(s).  I've been thinking about what would go into a `bloop.diagnostics` sub-module for a few months, and "why is this call failing" seems like candidate functionality.

**Comment by urluba** [comment]
Hi,

For info, if someone gets the error, it was just an issue with IAM... The following actions were not autorized:

```
"dynamodb:DescribeTimeToLive",
"dynamodb:DescribeContinuousBackups",
```
