### ISSUE TITLE
Support for Python 2.7

### ISSUE THREAD

**Issue by Miserlou** [numberoverzero/bloop#47]
It would be _extremely_ useful if Bloop worked with Python 2.7, because then we could use it with [Zappa](https://github.com/Miserlou/Zappa) and other AWS Lambda applications!

**Comment by funkybob** [comment]
Sadly, I'm +1 on this too.

I try to avoid any py2 code these days, but Lambda forces it upon us.

**Comment by funkybob** [comment]
I've started working on this, but the "declare" dependency is _also_ py3 only.

**Comment by numberoverzero** [comment]
Thanks for opening an issue - it's probably the biggest blocker for people to use bloop right now.  
_(Aside: Zappa looks awesome!  Nice work.)_

I'm strongly against new development in 2.7 - the [last planned release](http://legacy.python.org/dev/peps/pep-0373/) was 2.7.12, which just happened on 6-25-2016.  However, I recognize that with so much of AWS forcing people into python 2, there are a lot of people that can't migrate, and can't use this project from the outset.

I would **absolutely** help with development if either of you is interested in maintaining a fork (I'd probably inline Declare for simplicity).  I know that's asking for a significant commitment; you'd probably have higher adoption than I do for quite some time.

Sorry that's not a great answer.  For my own sanity and so that I'm not contributing to the inertia that keeps people on python 2, I really don't want to maintain any python 2 code as we approach the end-of-life date for bug fixes.

**Comment by funkybob** [comment]
Yeah, I'm more in favour of increasing pressure on AWS to catch up...

**Comment by numberoverzero** [comment]
Closing this out; bloop will not support Python 2.7. Thanks again for creating the issue.

For anyone visiting this in the future, I'll port bloop to 2.7 as long as someone else maintains (or just owns) the fork.  It might be practical once 1.0.0 comes out and the api has settled down.

**Comment by numberoverzero** [comment]
As Miserlou/zappa#793 mentioned AWS Lambda now supports 3.6 which re-opens the option to use Bloop with Zappa in some cases.  With #83 landing soon, startup times will be much faster now that `Engine.bind` can skip all validation.  (As noted there, the change is primarily for Lambda's usage pattern.)

@Miserlou, will Zappa support 2.7/3.6 in the same codebase?  If not, Bloop could be an option for the 3.x branch.

**Comment by Miserlou** [comment]
Zappa will support 2.7 and 3.6 simultaneously. I think both are currently working in `master` if you want to try it out! I only got it working about an hour ago though, there's still some.. wonkiness.
