### ISSUE TITLE
Question: What is the best way to filter list types?

### ISSUE THREAD

**Issue by jasonlockporcelane** [numberoverzero/bloop#73]
Hello,
I'm trying to filter on a models column that is a list type. The model looks like [this](https://gist.github.com/jasonlockporcelane/610d35d0a6a56929ca5d17fb05854e34) and the filter looks something like this: 
```
dentist_shifts_query = engine.scan(DentistShift).filter(lte_time_window & gte_time_window)
dentist_shifts_query = dentist_shifts_query.filter(DentistShift.cities.contains(address.city))
```
but that yields no results. I've tried this too: 
```
dentist_shifts_query = engine.scan(DentistShift).filter(lte_time_window & gte_time_window)
dentist_shifts_query = dentist_shifts_query.filter(DentistShift.cities[0].contains(address.city))
```
this returns only shifts with cities at that index. I'm wondering, is there a better way to filter on a models column that is a list. 

Please let me know if you need anymore info and thank you for your time!

**Comment by numberoverzero** [comment]
Hey, sorry this is causing problems.  I'm looking into the list filter issue right now.

First, it looks like you're replacing the first filter immediately with the second.  This came up in #43, and changing the syntax was considered in #44.  The syntax is not clear about this at all, which is getting fixed in 1.0; sorry about that.

To apply both filters, you'll want:

```
scan = engine.scan(DentistShift)
scan = scan.filter(
    lte_time_window &
    gte_time_window &
    DentistShift.cities.contains(address.city)
)
```

That at least explains why the time filters aren't applied.  However, if you want to get those working can you include how you constructed them?  I'm guessing something like `DentistShift.start >= arrow.now.replace(...)` etc.

**Comment by numberoverzero** [comment]
On the list filter issue, I have a pretty good guess.  I tried using `cities.contains("boston")` and hit a ValidationException:

```python
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Scan operation: ExpressionAttributeValues contains invalid value: One or more parameter values were invalid: Input collection [b, n, o, o, s, t] contains duplicates. for key :v1
```

Walking this through, it's an annoying coincidence (again) that strings are iterable.  The column's type is `List(String)`; if you dumped `["foo", "bar"]` through it, each value in the input (the whole list) would be dumped through the list's inner type (string).  However, "boston" is also iterable and the type calls `String.dump()` on each letter (since it iterate the input value "boston").

```ipython
In [1]: from bloop import List, String
In [2]: type = List(String)
In [3]: type.dynamo_dump(["first", "second"])
Out[3]: [{'S': 'first'}, {'S': 'second'}]
In [4]: type.dynamo_dump("whoa")
Out[4]: [{'S': 'w'}, {'S': 'h'}, {'S': 'o'}, {'S': 'a'}]
```

**Comment by numberoverzero** [comment]
Set does the same thing.  Ugh.

```
In [1]: from bloop import Set, String
In [2]: type = Set(String)
In [3]: type.dynamo_dump("boston")
Out[3]: ['b', 'n', 'o', 'o', 's', 't']
In [4]: type.dynamo_dump(["boston"])
Out[4]: ['boston']
```

I see two problems:

1. From the link above, documents don't support top-level conditions.  That means `List.contains` should simply raise, because a full path is required to construct a condition on a document.  This is why your filter with `DentistShift.cities[0]` was working.
2. Bloop's condition renderer has been blindly delegating to the column type to dump values.  This works for simple types: `DateTime.dynamo_dump(arrow.now())` will be fine.  However, `Set(String)` doesn't know if a given value should be the whole set such as `engine.save(some_set={3, 4, 5})`) or a single value such as `scan.filter(some_set.contains(3))`.

This needs a bit of thought.  Thanks for reporting it, and I'm sorry you ran into it so hard.  For now I don't think there's a **good** workaround.  I can come up with some **bad** workarounds, if you'd like.

When I do have a fix, it'll land in 0.9.13 because there are way too many breaking changes from 0.9.12 to 1.0.0 - you're going to want a changelog to approach that.

**Comment by jasonlockporcelane** [comment]
No worries! Thanks for looking into this, i've added my own bad work around for now :) Looking forward to 0.9.13.

**Comment by numberoverzero** [comment]
Sorry again, I'm really annoyed this has persisted for so long.

Here's what I came up with, fwiw:

```python
class StringListHack(String):
    def __init__(self, sep="|"):
        self.sep = sep
        super().__init__()

    def dynamo_dump(self, value, *, context=None, **kwargs):
        # HACK: this will ONLY take list or string, because it's
        # not robust at all.
        if isinstance(value, str):
            return value
        elif isinstance(value, list):
            return self.sep.join(value)
        else:
            raise RuntimeError("StringListHack is not very clever.")

    def dynamo_load(self, value, *, context=None, **kwargs):
        if value:
            return value.split(self.sep)
        return []
```

["boston", "chicago"] is stored as "boston|chicago" - the only trick is doing the type check in `dynamo_dump` to handle single values (for the filter) and multiple values (to save objects).

**Comment by numberoverzero** [comment]
Interesting.  Even though the docs suggest an exact path is needed for documents, there's no problem using `contains` with a list.

This is a much better shim than the above, since you won't need to migrate the data when List is fixed:

```python
class StringListHack(List):
    def __init__(self):
        super().__init__(String)

    def _dump(self, value, *, context=None, **kwargs):
        if isinstance(value, str):
            return {"S": value}
        return [{"S": v} for v in value]

    def dynamo_load(self, value, *, context=None, **kwargs):
        return value
```

**Comment by jasonlockporcelane** [comment]
Thanks @numberoverzero! How/where would implement something like that?

**Comment by numberoverzero** [comment]
[Heres the shim](https://gist.github.com/numberoverzero/89c360795c83d44ff96cad6d1c0f6914) until 0.9.13.

The example redefines `List` so that when 0.9.13 comes around, you can just delete the patched class and the rest of the code keeps working.

If you want a `Set(String)` which I think you might, just change the line `class List(List):` to `class Set(Set):` and that should be fine, too.

**Comment by jasonlockporcelane** [comment]
Aahh ok, will try that out now. Thank you!

**Comment by jasonlockporcelane** [comment]
Awesome, the shim works like charm. I cannot thank you enough for taking the time to look at this issue!

**Comment by numberoverzero** [comment]
[Tagged 0.9.13](https://github.com/numberoverzero/bloop/releases/tag/v0.9.13) and [released on pypi](https://pypi.python.org/pypi/bloop/0.9.13).

You should be able to `pip install -U bloop` and get rid of the shim.  Take care that nested `List` will likely still exhibit this problem, such as `List(List(String))`

**Comment by jasonlockporcelane** [comment]
Fantastic. Thank you @numberoverzero!
