### ISSUE TITLE
How to affect a query Limit?

### ISSUE THREAD

**Issue by funkybob** [numberoverzero/bloop#91]
I'm converting some code over from another tool, and have a query that wants never more than 10 records.

Previously I passed Limit=10 and it all worked.

There appears no way to specify that in Bloop, and the history suggests this was deliberately removed?

**Comment by numberoverzero** [comment]
Thanks for opening an issue; this needs to be clarified in the docs.  The [Limit Parameter](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-Limit) is a bit subtle (at least to me) and I've gone back and forth on keeping it numerous times.  The final decision was that anyone that actually needs the Limit parameter as it exists (and not as it's usually used) will nearly certainly not use Bloop for performance reasons.

To answer your question directly, I'd recommend using [`itertools.islice`](https://docs.python.org/3/library/itertools.html#itertools.islice):

```python
from itertools import islice

for user in islice(engine.scan(User), 5):
    pass
```

----
----

## Probably more detail than you want

I believe most people expect limit to say "when I iterate over my `Engine.query` or `Engine.scan` there must mot be more than `limit` items".  Meanwhile the DynamoDB API defines Limit to mean "for a single call only evaluate up to `Limit` items before applying any filters".  Because Bloop doesn't expose the individual query calls with continuation token and instead gives you a single `Iterable` that automatically handles pagination, the concept of a limit doesn't really apply.  Because each `next()` for a query or scan will follow any number of continuation tokens, limiting the items evaluated per continuation token doesn't provide any additional throughput control to the client.

There's an argument to be made that anyone using Bloop shouldn't mistake a `limit:int=0` param for translating into the DynamoDB API equivalent due to the above point (such an interpretation would necessarily be meaningless) but this now burdens the user with thinking through the implementation details of Bloop to understand how a local parameter maps to the wire api.

Here are the previous issues around the query/scan api and the limit param specifically, only intended to provide additional context for the curious:

1. #43 - While debugging an unrelated issue, it's noted that the old chaining syntax for building up queries is unclear and silently does the wrong thing.  Specifically, https://github.com/numberoverzero/bloop/issues/43#issuecomment-227541536
2. #44 - Although limit isn't mentioned specifically, this issue dives into two options for building up query and scan in pieces.  Neither option is used today, but the tradeoffs explored will lead to the current syntax, specifically in the next issue.
3. #54 - The 1.0 syntax is born, heavily inspired by the transformation Requests' `Session` object underwent for 1.0.
4. #58 - The issue where I realize I've misunderstood how `Limit` works, and try to find the right value to optimize speed.  The intent here was to reduce the `Limit` wire parameter as the local iterable approached its limit so eg. if the local limit was 50 and we'd yielded 35 results so far, the api `Limit` might be reduced to `30` to reduce consumed throughput.  Since this could backfire (for a heavily filtered query) and cause many more calls, I opted to leave the default alone.
5. #73 - Only a brief mention here about the planned syntax change in 1.0 as the op's code provides an additional data point that the silent failure with filter chaining was dangerous: https://github.com/numberoverzero/bloop/issues/73#issuecomment-257186412

**Comment by funkybob** [comment]
Nope... that level of detail was awesome :)
